---
resources:
# The repo with our Dockerfile
- name: concourse-examples
  type: git
  icon: github
  source:
    uri: https://github.com/concourse/examples.git
    branch: oci-test

# Where we will push the image
- name: ubuntu-image
  type: registry-image
  icon: docker
  source:
    repository: ubuntu

jobs:
- name: build-and-push
  plan:
  - in_parallel:
    - get: concourse-examples
    - get: ubuntu-image
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          # Check out the README for oci-build-task at
          # https://github.com/vito/oci-build-task
          repository: vito/oci-build-task
      inputs:
      - name: concourse-examples
      - name: ubuntu-image
        path: concourse-examples/Dockerfiles/ubuntu
      outputs:
      - name: image
      params:
        CONTEXT: concourse-examples/Dockerfiles/simple
      run:
        path: build
